name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.event.repository.fork == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure PSGallery is registered
        shell: pwsh
        run: |
          if (-not (Get-PSResourceRepository -Name 'PSGallery' -ErrorAction SilentlyContinue)) {
            Register-PSResourceRepository -Name 'PSGallery' -Uri 'https://www.powershellgallery.com/api/v2'
          }
      - name: Publish PowerShell Module
        uses: natescherer/publish-powershell-action@v1.1.1
        with:
          token: ${{ secrets.PS_GALLERY_KEY }}
          target: gallery
          path: src/GitlabCli
    environment:
      name: PowerShell Gallery
      url: https://www.powershellgallery.com/packages/GitlabCli

  push:
    if: github.event.repository.fork == false

    env:
      IMAGE_NAME: gitlab-cli
      IMAGE_VERSION: ${{ github.ref_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: ${{ github.ref_name == 'main' }}
        env:
          IMAGE_VERSION: latest
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME

          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
